# fill in the blanks to dockerize this node app
# working from course - FROM node:10.15-alpine 
FROM node:14.7-alpine3.12

EXPOSE 3000

RUN apk add --no-cache tini  

WORKDIR /app 

COPY package.json package-lock*.json ./

RUN npm install && npm cache clean --force 

COPY . . 

ENTRYPOINT ["/sbin/tini", "--"]

CMD ["node", "app.js"]
